### ISSUE TITLE
repo structure

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-reports-telegram#1]
I propose we have a single repo for reports lambdas, reasons:
* Avoid duplicating shared licence files, README instructions, npm dependencies, serverless.yml config (part) incl. environment variables like DB (store separately, add that file to .gitignore and read in to avoid these going into github).
* May well be some shared code too.
* Deploy all or single function updates from serverless.yml
* Avoids having lots of little repos. Lambdas are small.

Negatives: 
* Need to be clear in raising issues as to where the problem is / what lambda the feature request is for.

**Comment by MaanasaPriyaa** [comment]
I was thinking of the same as I was pushing the code today. @talltom & I talked about this but we dint decide on anything because at that point we had just one set of lambdas in. I'll put it all into one reports-lambda module (if it doesn't exist already). Or suggest a repo name pls :)

**Comment by matthewberryman** [comment]
Great minds think alike :) 
There's already a https://github.com/urbanriskmap/cognicity-reports-lambda that has Qlue in—less serverless deployment, leave that for now and copy the rest in I guess.

**Comment by MaanasaPriyaa** [comment]
Nice. Cool. Qlue subfolder will continue existing as is. I'll move all the social media lambda code into this repo tomorrow.

**Comment by matthewberryman** [comment]
Ok. I just need to check on jenkins deployment for qlue lambda, will do that now.

**Comment by matthewberryman** [comment]
double checked and as long as you don't touch the qlue subfolder then it won't break separate deployment of that via jenkins (I will eventually move it to serverless)

**Comment by MaanasaPriyaa** [comment]
Pushed code to dev branch. Qlue folder is untouched. Nothing is deployed on AWS Dev stage yet. Will test & update code tomorrow. Meanwhile, could you please review and let me know if it looks fine?

**Comment by matthewberryman** [comment]
@MaanasaPriyaa I have left some comments in-line in your commit; in addition to those I recommend you separate out the handler functions into different files, one for each SM platform, for code readability, and code and deployment maintainability.

**Comment by tomasholderness** [comment]
I think the new structure over in cognicity-reports-lambda looks great. The only issue (which @MaanasaPriyaa just mentioned to me) is if different deployments enable/disable different social media channels.

@matthewberryman is there someway you're aware of where the .env file could list which lambdas/sources to turn of/off for a particular deployment?

**Comment by matthewberryman** [comment]
@talltom @MaanasaPriyaa you can [suck in other variables from yml and json files](https://serverless.com/framework/docs/providers/aws/guide/variables), but then you can't make the list of deployed functions depend on those. Might be worth forking for each deployment and just commenting them out—if indeed you care, i.e. the SNS ones will never get triggered if you don't set up SNS topics, and the API ones won't get called unless you tell some other service about the API endpoint, in which case the only downside is a small amount of s3 storage used up.

You can have separate serverless.yml files (see notes on [organisation](https://serverless.com/framework/docs/providers/aws/guide/services#organization)) but then short of removing those files from the repo they'll still be deployed and (at present) doing it that way creates separate API endpoints as per the notes.

Separately, on .env files and getting the environment variables into the deployed lambdas, rather than sucking a .env file in using serverless variables, you might want to look at https://www.npmjs.com/package/serverless-plugin-dotenv as a cleaner way of doing it.

**Comment by MaanasaPriyaa** [comment]
Sorry for the delay @matthewberryman, been busy with the thesis work. 
Ok, that makes sense. I was initially thinking of controlling it via env files (not set tokens for Facebook in a deployment, for example). But this makes more sense. I'll go through the documentation and update the code tonight.

**Comment by tomasholderness** [comment]
Closing this as not relevant to new architecture for chatbots (CogniCity v3.1.0) that is currently being rolled out.
