### ISSUE TITLE
Suppress/modify response msg for reports in unsupported location?

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/cognicity-reports-telegram#3]
<img width="794" alt="screenshot 2017-08-24 18 36 55" src="https://user-images.githubusercontent.com/22597094/29692135-8b01e75e-88fc-11e7-90e0-be369a38d725.png">

In case of user selecting an unsupported location, should we disable report submission client-side or catch 'undefined' city param in server / reports modules?

**Comment by ojha-url** [comment]
While telegram responds with...
> Hi! Thanks for your report, I've put it on the map.

clicking the link says report not found in 'undefined'. There's scope for better messaging.

![screenshot 2017-08-24 18 49 28](https://user-images.githubusercontent.com/22597094/29692265-1c8f44aa-88fd-11e7-9e23-19d1603597b0.png)

**Comment by tomasholderness** [comment]
There is now a warning in the location card if you're out of state, and some improvements in the back end here: https://github.com/urbanriskmap/cognicity-server/issues/87

Also added ability to catch a null instanceRegionCode, here: 745dc5f2bff85f77165f76ada417150606d85ba7
